version: "3.8"
services: 

    myimage:
        build:
            context: ./
        env_file:
            - ./.env
        ports:
            - 8000:8000
        depends_on:
            - db
            - redis

    db:
        image: postgres:13
        env_file:
            - ./.env
    
    redis:
        image: "redis:6"
        env_file:
            - ./.env
        ports:
            - 6379:6379
        
    nginx:
        image: nginx:1.19
        volumes:
            - ./nginx/nginx-myimage.conf:/etc/nginx/conf.d/default.conf
        env_file:
            - ./.env
        ports:
            - 80:80
        depends_on:
            - myimage

